name: Build WebGoat Maven
  
on:
  push:
  workflow_dispatch:


env:
#  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 7
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: maven

      - name: Find settings.xml
        run: |
          cd /
          echo "Finding settings.xml from root directory"
          sudo find . -name settings.xml


      - name: Run JUnit test with Maven
        run: |
          echo "Project name is ${GITHUB_REPOSITORY#*/}"
          echo "Project name is ${GITHUB_REPOSITORY}"
          mvn test
      
