name: Build WebGoat Maven
  
on:
  push:
  workflow_dispatch:


env:
#  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 7
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: maven

      - name: Print settings.xml
        run: |
          cd /
          echo "Printing settings.xml"
          sudo cat /home/runner/.m2/settings.xml

      - name: Checkout code common module
        uses: actions/checkout@v4
        with: 
          repository: "Zivra/Common-Module-workflows"
          ref: "jorge-test-branch1"
          path: Common-Module-workflows
          token: ${{secrets.GH_ACTIONS_PAT}}

      - name: list common module directory
        run: |
          cd $GITHUB_WORKSPACE
          ls -la 
          echo "listing home directory"
          sudo ls -la /home/runner/
          echo "listing m2 directory"
          sudo ls -la /home/runner/.m2

      - name: Copy settings.xml file
        run: |
          cp $GITHUB_WORKSPACE/Common-Module-workflows/settings.xml /home/runner/.m2/settings.xml
          ls -la
          cat /home/runner/.m2/settings.xml
          echo "working dir is $GITHUB_WORKSPACE"

#      - name: Copy Settings.xml to m2 folder
#        run: |
#          cp  /home/runner/work/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}/settings.xml /home/runner/.m2/settings.xml
#          ls -la /home/runner/.m2

      - name: Run JUnit test with Maven
        run: |
          echo "Here's settings.xml"
          cat /home/runner/.m2/settings.xml
          echo "Project name is ${GITHUB_REPOSITORY#*/}"
          echo "Project name is ${GITHUB_REPOSITORY}"
          mvn test
      
