name: Build WebGoat Maven
  
on:
  push:
  workflow_dispatch:


env:
#  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 7
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          cache: maven

      - name: Print settings.xml
        run: |
          cd /
          echo "Printing settings.xml"
          sudo cat /home/runner/.m2/settings.xml

      - name: Copy Settings.xml to m2 folder
        run: |
          cp  /home/runner/work/WebGoat-Legacy/WebGoat-Legacy/settings.xml ./.m2/settings.xml

#      - name: Generate maven settings.xml
#        uses: whelk-io/maven-settings-xml-action@v21
#        with:
#          repositories: >
#            [
#              {
#                "id": "central",
#                "url": "https://repo1.maven.org/maven2"
#              },
#              {
#                "id": "github",
#                "url": "https://maven.pkg.github.com/zivra/*",
#                "snapshots": {
#                  "enabled": "true"
#                }
#              }
#            ]
#          plugin_repositories: >
#            [
#              {
#                "id": "central",
#                "url": "https://repo1.maven.org/maven2",
#                "snapshots": {
#                  "enabled": "true"
#                }
#              },
#              {
#                "id": "github",
#                "url": "https://maven.pkg.github.com/zivra/*",
#                "snapshots": {
#                  "enabled": "true"
#                }
#              }
#            ] 
#          servers: >
#            [
#              {
#                "id": "github",
#                "username": "${env.GITHUB_ACTOR}",
#                "password": "${env.GITHUB_TOKEN}"
#              }
#            ]
#          output_file: .m2/settings.xml


      - name: Run JUnit test with Maven
        run: |
          echo "Here's settings.xml"
          cat .m2/settings.xml
          echo "Project name is ${GITHUB_REPOSITORY#*/}"
          echo "Project name is ${GITHUB_REPOSITORY}"
          mvn test
      
